// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQ-wBbbBFr8EO2cFXZahDYCd9HwK83gE',
    appId: '1:752972764270:android:dd240393965d2192b2c27f',
    messagingSenderId: '752972764270',
    projectId: 'mobile-cw-4f53c',
    databaseURL: 'https://mobile-cw-4f53c-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-cw-4f53c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCotnRG_uyST4y8_WM34bFJO5E9jIDsSs',
    appId: '1:752972764270:ios:fc2d69ec25d41358b2c27f',
    messagingSenderId: '752972764270',
    projectId: 'mobile-cw-4f53c',
    databaseURL: 'https://mobile-cw-4f53c-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-cw-4f53c.firebasestorage.app',
    iosClientId: '752972764270-mpgs0fu5l5kkk9tgv4dc0ave39blhp62.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwApp',
  );

}